name: Postman Workflow

on:
  push:
    branches:
      - main

jobs:
  Postman:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create dir
      run: |
       mkdir TestArtifact
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
       node-version: '20'
       
    - name: Install Newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-htmlextra
            
    - name: Run Postman tests    
      run: newman run Postman/Petstore.postman_collection.json -e Postman/petstore.postman_environment.json -r htmlextra --reporter- htmlextra-export SampleArtifact/report.html
    
