name: Run MySQL Container

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up MySQL
      run: |
        docker run -d --name My_SQL -e MYSQL_ROOT_PASSWORD=999999999 mysql:latest

    - name: Verify MySQL container is running
      run: docker ps
    - name: Connect to MySQL server
      run: docker exec -it My_SQL mysql -u root -p
