name: Download and Run Container

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Docker image
      run: docker pull mysql:latest

    - name: Run Docker container
      run: docker run mysql:latest
