name: Postman CI/CD

on:
  push:
    branches:
      - main

jobs:
  postman_test:
    runs-on: ubuntu-latest

    steps:
      - name: Run Postman Collection
        run: |
          newman run Postman/Petstore.postman_collection.json -e Postman/petstore.postman_environment.json
