name: Postman CI/CD

on:
  push:
    branches:
      - Tanya

jobs:
  postman_test:
    runs-on: ubuntu-latest

    steps:
        - name: Run Postman Collection
        run: |
          newman run /c/test/project/FinalI_project/Postman/Petstore.postman_test_run.json
