name: My CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check script
      uses: actions/checkout@v2

    - name: Run contact script
      run: |
        echo contacts.sh
        
   - name: Run contact script
      run: |
        echo find_dir_file.sh

