name: My CI Workflow

on:
  push:
    branches:
      - main

jobs:
  My_script1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run contact script
      run: |
        echo contacts.sh
        
  My_script2:
    runs-on: ubuntu-latest
    needs:
     - My_script1
    steps:
    - uses: actions/checkout@v3
    - name: run find_dir_file.sh
      run: |
       echo find_dir_file.sh
        
  Postman:
    runs-on: ubuntu-latest
    needs:
     - My_script1
     - My_script2
    steps:
    - uses: actions/checkout@v3
    - name: Create dir
      run: |
       mkdir TestArtifact

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
       node-version: '20'
       
    - name: Install Newman
      run: |
       npm install -g newman
       npm install -g newman-reporter-slackreporter
       npm install -g newman-reporter-htmlextra
      
      
    - name: Run Postman tests    
      run: newman run Postman/Petstore.postman_collection.json -e Postman/petstore.postman_environment.json -r htmlextra --reporter-htmlextra-export SampleArtifact/report.html

    - name: Output the results
      uses: actions/upload-artifact@v3
      with:
         name: Reports
         path: TestArtifacts


    
