name: My CI Workflow

on:
  push:
    branches:
      - main

jobs:
  My_script1:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run contact script
      run: |
        echo contacts.sh
        
  My_script2:
    runs-on: ubuntu-latest
    needs:
     - My_script1
    steps:
    - uses: actions/checkout@v3
    - name: run find_dir_file.sh
      run: |
       echo find_dir_file.sh
        
  Postman:
    runs-on: ubuntu-latest
    needs:
     - My_script1
     - My_script2
    steps:
    - uses: actions/checkout@v3
    - name: run Postman
      run: |
       newman run Petstore.postman_collection.json -e petstore.postman_environment.json

