name: My scripts Workflow

on:
  push:
    branches:
      - main

jobs:
  Contacts_script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run contact script
      run: |
        echo contacts.sh
        
  find_dir_file_script:
    runs-on: ubuntu-latest
    needs:
     - Contacts_script
    steps:
    - uses: actions/checkout@v4
    - name: run find_dir_file.sh
      run: |
       echo find_dir_file.sh
        

